services:
  web:
    build: .
    ports:
      - "6969:3000"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: sh -c "ls -la /app && node /app/server.js" 