services:
  web:
    build:
      context: .
      no_cache: true
    image: timer:latest
    pull_policy: always
    ports:
      - "6969:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 